config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get '/dashboard', to: 'users#dashboard'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  # Orders
  resources :orders, only: [:create, :new]
  post '/search', to: 'orders#search'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  # Associations
  belongs_to :sender, foreign_key: "sender_id", class_name: "UserDetail"
  belongs_to :receiver, foreign_key: "receiver_id", class_name: "UserDetail"
  belongs_to :service
  belongs_to :payment_mode
  belongs_to :status
  
  # Including Helpers
  include OrdersHelper
  
  accepts_nested_attributes_for :receiver, :reject_if => :all_blank

  # Callbacks
  before_save :add_uuid
  after_commit :send_order_email

  # Validations
  validates_presence_of :parcel_weight


  def add_uuid
    # To generate random UUID
    self.order_uuid = self.generate_secure_random_uuid
  end

  def send_order_email
    UserMailer.order_email(self.sender, self.order_uuid).deliver_now
    UserMailer.order_email(self.receiver, self.order_uuid).deliver_now
  end
end

app/models/payment_mode.rb
class PaymentMode < ApplicationRecord
  # Associations
  has_many :orders

  # Validations
  validates :name, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
  # Associations
  has_many :orders

  # Validations
  validates :name, presence: true
end

app/models/status.rb
class Status < ApplicationRecord
  # Associations
  has_many :orders

  # Validations
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associations
  has_one :user_detail

  accepts_nested_attributes_for :user_detail, :reject_if => :all_blank

  before_create :add_email_to_user_detail

  protected

  def add_email_to_user_detail
    self.user_detail.email = self.email
  end
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
  # Associations
  belongs_to :user, optional: true
  has_many :sent_orders, foreign_key: "sender_id", class_name: "Order"
  has_many :received_orders, foreign_key: "receiver_id", class_name: "Order"

  # Validations
  validates :full_name, :phone, :pin_code, :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, user_detail_attributes: [:id, :full_name, :address, :pin_code, :phone]])
  end

  def after_sign_in_path_for(resource) 
    '/dashboard'
  end 

  def after_sign_up_path_for(resource) 
    '/dashboard' 
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
  end

  def create
    order = current_user.user_detail.sent_orders.build(order_params)
    if order.save
      redirect_to '/dashboard', notice: "Order created successfully"
    else
      redirect_to '/dashboard', alert: "Failed to create order"
    end
  end

  def search
    @orders = Order.where(order_uuid: params[:search_term].strip)
  end

  private

  def order_params
    params.require(:order).permit(:status_id, :service_id, :payment_mode_id, :parcel_weight, :order_uuid, :sender_id, receiver_attributes: [:id, :full_name, :pin_code, :address, :phone, :email])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @orders = current_user.user_detail.sent_orders
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
  def generate_secure_random_uuid 
    SecureRandom.uuid
  end
end

app/views/home/index.html.erb
<div class="dashboard-title">
	<p>Welcome to Courier App</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourierApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/shared/header" %>
<!--     <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Courier App</a>
 
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    	<% unless current_user.present? %>
	      <li class="nav-item <%= params[:controller] == 'devise/sessions'? 'active' : ''%>">
	      	<%= link_to 'Login', '/users/sign_in', class: "nav-link" %>
	      </li>
	      <li class="nav-item <%= params[:controller] == 'devise/registrations'? 'active' : ''%>">
	      	<%= link_to 'Sign Up', '/users/sign_up', class: "nav-link"  %>
	      </li>
	    <% else %>
	    	<% is_dashboard = params[:action] == 'dashboard' %>
	    	<li class="nav-item <%= is_dashboard ? 'active' : '' %>">
	    		<%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
	      </li>
	    	<% if is_dashboard %>
		      <li class="nav-item">
		    		<%= link_to "Create Order", new_order_path, class: "nav-link" %>
		      </li>
		    <% end %>
	      <li class="nav-item">
	      	<%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
	      </li>
	    <% end %>
    </ul>
    <%= form_for :search, url: search_path, html: {class: "form-inline my-2 my-lg-0"} do |f| %>
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search_term">
      <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
    <% end %>
  </div>
</nav>

app/views/orders/_order_detail.html.erb
<% if @orders.present? %>
  <div class="dashboard-title">
  	<p>List of Orders</p>
  </div>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">S No.</th>
        <th scope="col">Sender</th>
        <th scope="col">Receiver</th>
        <th scope="col">Service</th>
        <th scope="col">Payment Mode</th>
        <th scope="col">Order UUID</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
    	<% @orders.each_with_index do |o, index| %>
  	    <tr>
  	      <th scope="row"><%= index + 1 %></th>
  	      <td><%= o.sender.full_name %></td>
  	      <td><%= o.receiver&.full_name %></td>
  	      <td><%= o.service.name %></td>
  	      <td><%= o.payment_mode.name %></td>
          <td><%= o.order_uuid %></td>
  	      <td><%= o.status.name %></td>
  	    </tr>
  	  <% end %>
    </tbody>
  </table>
<% else %>
  <div class="dashboard-title">
    <p>No Orders Found</p>
  </div>
<% end %>

app/views/orders/new.html.erb
<div class="global-container">
  <div class="card login-form col-sm-4">
    <div class="card-body">
      <h3 class="card-title text-center">New Order</h3>
      <div class="card-text">
				<%= form_for @order do |f| %>
          <h3 class="text-center">Receiver Information</h3>
          <%= f.fields_for :receiver, @order.build_receiver do |r| %>
            <div class="row">
	          	<div class="form-group col-sm-6">
	          		<label for="service">Full Name</label>
					    	<%= r.text_field :full_name, :required => true, :autofocus => true, class: "form-control form-control-sm" %>
					    </div>
					    <div class="form-group col-sm-6">
	          		<label for="address">Address</label>
					    	<%= r.text_field :address, :required => true, :autofocus => true, class: "form-control form-control-sm" %>
					    </div>
					    <div class="form-group col-sm-6">
	          		<label for="pin_code">Pin Code</label>
					    	<%= r.text_field :pin_code, :required => true, :autofocus => true, class: "form-control form-control-sm" %>
					    </div>
					    <div class="form-group col-sm-6">
	          		<label for="phone">Phone</label>
					    	<%= r.text_field :phone, :required => true, :autofocus => true, class: "form-control form-control-sm" %>
					    </div>					
            </div>
            <div class="form-group">
              <label for="email">Email</label>
              <%= r.text_field :email, :required => true, :autofocus => true, class: "form-control form-control-sm" %>
            </div>  
				  <% end %>
          <h3 class="text-center">Order Detail</h3>
          <div class="form-group">
            <label for="service">Service</label>
            <%= select("order", "service_id", Service.all.collect {|p| [ p.name, p.id ] }, { include_blank: true }, class: "form-control form-control-sm") %>
          </div>  
          <div class="form-group">
            <label for="payment_mode">Payment Mode</label>
            <%= select("order", "payment_mode_id", PaymentMode.all.collect {|p| [ p.name, p.id ] }, { include_blank: true }, class: "form-control form-control-sm") %>
          </div>
				  <div class="form-group">
            <label for="parcel_weight">Parcel Weight</label>
            <%= f.text_field :parcel_weight, :required => true, :autofocus => true, class: "form-control form-control-sm" %>
            <%= f.hidden_field :status_id, value: 1 %>
          </div>
          <button type="submit" class="btn btn-primary btn-block">Submit</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/orders/search.html.erb
<!-- Common Partial for order search and dashboard display of orders -->
<%= render partial: "order_detail" %>

app/views/users/dashboard.html.erb
<!-- Common Partial for order search and dashboard display of orders -->
<%= render partial: "orders/order_detail" %>